/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ReflectionsRouteImport } from './routes/reflections'
import { Route as ReflectionsSlugRouteImport } from './routes/reflections.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ReflectionsRoute = ReflectionsRouteImport.update({
  id: '/reflections',
  path: '/reflections',
  getParentRoute: () => rootRouteImport,
} as any)
const ReflectionsSlugRoute = ReflectionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ReflectionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/reflections': typeof ReflectionsRouteWithChildren
  '/reflections/$slug': typeof ReflectionsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/reflections': typeof ReflectionsRouteWithChildren
  '/reflections/$slug': typeof ReflectionsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/reflections': typeof ReflectionsRouteWithChildren
  '/reflections/$slug': typeof ReflectionsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/projects' | '/reflections' | '/reflections/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/projects' | '/reflections' | '/reflections/$slug'
  id: '__root__' | '/' | '/projects' | '/reflections' | '/reflections/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsRoute: typeof ProjectsRoute
  ReflectionsRoute: typeof ReflectionsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reflections': {
      id: '/reflections'
      path: '/reflections'
      fullPath: '/reflections'
      preLoaderRoute: typeof ReflectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reflections/$slug': {
      id: '/reflections/$slug'
      path: '/$slug'
      fullPath: '/reflections/$slug'
      preLoaderRoute: typeof ReflectionsSlugRouteImport
      parentRoute: typeof ReflectionsRoute
    }
  }
}

interface ReflectionsRouteChildren {
  ReflectionsSlugRoute: typeof ReflectionsSlugRoute
}

const ReflectionsRouteChildren: ReflectionsRouteChildren = {
  ReflectionsSlugRoute: ReflectionsSlugRoute,
}

const ReflectionsRouteWithChildren = ReflectionsRoute._addFileChildren(
  ReflectionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsRoute: ProjectsRoute,
  ReflectionsRoute: ReflectionsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
